apiVersion: v2
name: cloudrun
description: Templates a Google CloudRun YAML manifest that can be deployed using the Google Cloud CLI.
type: application
version: 0.1.0
maintainers:
  - name: 'Michael Reichenbach (Silthus)'
    email: 'me@silthus.net'
    url: 'https://github.com/silthus'
