# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/losisin/helm-values-schema-json
    rev: v1.6.3
    hooks:
      - id: helm-schema
        args: []
  - repo: local
    hooks:
      - id: schema-docs
        name: Generate schema documentation
        entry: bash -c 'npx @adobe/jsonschema2md --header false --input . --out schema/'
        language: system
        files: ^values.schema.json$
