---
# Source: wrapper-chart/charts/cloudrun1/templates/cloudrun.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-cloudrun
  labels:
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
    run.googleapis.com/region: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "true"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300

      containers:
        - image: us-docker.pkg.dev/cloudrun/container/hello
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"

          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
---
# Source: wrapper-chart/charts/cloudrun2/templates/cloudrun.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-cloudrun2
  labels:
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
    run.googleapis.com/region: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "true"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300

      containers:
        - image: us-docker.pkg.dev/cloudrun/container/hello
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"

          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
